spring:
  profiles:
    active: service1
  application:
    name: service
management:
  security:
    enabled: false

---
server:
  port: 8761
spring:
  profiles: service1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/,http://localhost:8762/eureka/

---
server:
  port: 8763
spring:
  profiles: service2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/,http://localhost:8762/eureka/
