spring:
  profiles:
    active: client1
  application:
    name: client
management:
  security:
    enabled: false

---
server:
  port: 8769
spring:
  profiles: client1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/,http://localhost:8762/eureka/

---
server:
  port: 8770
spring:
  profiles: client2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/,http://localhost:8762/eureka/
