spring:
  application:
    name: eureka-server
  profiles:
    active: center

---
server:
  port: 8760
spring:
  profiles: center1

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://peer0:8760/eureka/
  instance:
    hostname: center

---
server:
  port: 8762
spring:
  profiles: center2
eureka:
  instance:
    hostname: center
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://peer2:8762/eureka/
